version: '3.1'
services:
  mongo:
    image: mongo
    restart: always
    ports: 
      - 27017:27017
  
  rabbitmq:
        image: rabbitmq:3.7.5-management
        hostname: app-rabbitmq
        ports:
            - 5672:5672
            - 15672:15672
        volumes:
            - ./data/rabbitmq:/var/lib/rabbitmq/mnesia/rabbit@app-rabbitmq:cached
        environment:
            RABBITMQ_ERLANG_COOKIE: 6085e2412b6fa88647466c6a81c0cea0
            RABBITMQ_DEFAULT_USER: rabbitmq
            RABBITMQ_DEFAULT_PASS: rabbitmq
            RABBITMQ_DEFAULT_VHOST: /
  
  event-storage:
        image: e1426972/eventstorageservice
        hostname: eventstorageservice
        depends_on:
          - rabbitmq
          - mongo
        ports:
          - 8081:8080
  entity-storage:
        image: e1426972/entitystorageservice
        hostname: entitystorageservice
        depends_on:
          - rabbitmq
          - mongo
        ports:
          - 8082:8080
  notification-storage:
        image: e1426972/notificationstorageservice
        hostname: notificationstorageservice
        depends_on:
          - rabbitmq
          - mongo
        ports:
          - 8083:8080