spring:
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true
            routes:
            -   id: event-storage
                uri: lb://event-storage
                predicates:
                -   Path=/eventstorage/**
                filters:
                -   RewritePath=/(?<path>.*), /$\{path}
                -   name: Hystrix
                    args:
                        name: cacheFallback
                        fallbackUri: forward:/hystrixfallback
            -   id: entity-storage
                uri: lb://entity-storage
                predicates:
                    -   Path=/entitystorage/**
                filters:
                    -   RewritePath=/(?<path>.*), /$\{path}
                    -   name: Hystrix
                        args:
                          name: cacheFallback
                          fallbackUri: forward:/hystrixfallback
            -   id: notification-storage
                uri: lb://notification-storage
                predicates:
                    -   Path=/notificationstorage/**
                filters:
                    -   RewritePath=/(?<path>.*), /$\{path}
                    -   name: Hystrix
                        args:
                            name: cacheFallback
                            fallbackUri: forward:/hystrixfallback

hystrix:
    command:
        fallbackcmd:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 1

logging:
    pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

management:
  endpoints:
    web:
      exposure:
        include: "*"