spring:
    cloud:
        gateway:
            globalcors:
              corsConfigurations:
                '[/**]':
                  allowedOrigins: "*"
                  allowedMethods:
                    - GET
                    - PUT
                    - POST
                    - PATCH
                    - DELETE
            discovery:
                locator:
                    enabled: true
            routes:
            -   id: event-storage
                uri: lb://event-storage
                predicates:
                -   Path=/eventstorage/**
                filters:
                  - name: Hystrix
                    args:
                      name: eventCacheFallback
                      fallbackUri: forward:/cacheFallback
                  - RewritePath=/(?<path>.*), /$\{path}
            -   id: entity-storage
                uri: lb://entity-storage
                predicates:
                    -   Path=/entitystorage/**
                filters:
                    -   RewritePath=/(?<path>.*), /$\{path}
                    -   name: Hystrix
                        args:
                          name: entityCacheFallback
                          fallbackUri: forward:/cacheFallback
            -   id: notification-storage
                uri: lb://notification-storage
                predicates:
                    -   Path=/notificationstorage/**
                filters:
                    -   RewritePath=/(?<path>.*), /$\{path}
                    -   name: Hystrix
                        args:
                            name: notificationCacheFallback
                            fallbackUri: forward:/cacheFallback

redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}

hystrix:
    command:
        cacheFallback:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 5000

logging:
    pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
    level:
      ROOT: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"