apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gateway-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
        - path: /eventstorage
          backend:
            serviceName: event-storage
            servicePort: 80
        - path: /notificationstorage
          backend:
            serviceName: notification-storage
            servicePort: 80
        - path: /entitystorage
          backend:
            serviceName: entity-storage
            servicePort: 80
        - path: /backendui
          backend:
            serviceName: backendui-service
            servicePort: 80
