apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-storage
  labels:
    app: notification-storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-storage
  template:
    metadata:
      labels:
        app: notification-storage
    spec:
      containers:
        - name: notification-storage
          image: registry.gitlab.com/fizzerle/dse-2019-ss/notificationstorageservice:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
          env:
            - name: MONGO_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mongodb
                  key: database-name
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: mongodb
                  key: database-host
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: database-user
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: database-password
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: redis
                  key: database-host
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: redis
                  key: database-port
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis
                  key: database-password
      imagePullSecrets:
        - name: registry.gitlab.com
---
apiVersion: v1
kind: Service
metadata:
  name: notification-storage
  labels:
    app: notification-storage
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: notification-storage