apiVersion: apps/v1
kind: Deployment
metadata:
  name: swagger-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swagger-gateway
  template:
    metadata:
      labels:
        app: swagger-gateway
    spec:
      containers:
        - name: swagger-gateway
          image: e1426972/swaggergateway:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: swagger-gateway-service
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: swagger-gateway
  type: NodePort