apiVersion: apps/v1
kind: Deployment
metadata:
  name: swagger-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swagger-gateway
  template:
    metadata:
      labels:
        app: swagger-gateway
    spec:
      containers:
        - name: swagger-gateway
          image: registry.gitlab.com/fizzerle/dse-2019-ss/swaggergateway:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
      imagePullSecrets:
        - name: registry.gitlab.com
---
apiVersion: v1
kind: Service
metadata:
  name: swagger-gateway-service
spec:
  ports:
    - port: 8081
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: swagger-gateway
  type: LoadBalancer
  loadBalancerIP: 35.246.153.101